name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    CARGO_TERM_COLOR: always

jobs:
    test:
        name: cargo clippy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  components: clippy
            - name: Install Dependencies
              run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
            - run: cargo clippy

    # Check formatting with rustfmt
    formatting:
        name: cargo fmt
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            # Ensure rustfmt is installed and setup problem matcher
            - uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  components: rustfmt
            - name: Rustfmt Check
              uses: actions-rust-lang/rustfmt@v1
